class ListApp {
  static const List<String> audioQuraan = [
    'audio_quraan/yasser-al-dossari-001.mp3',
    'audio_quraan/البقرة.mp3',
    'audio_quraan/أل-عمران.mp3',
    'audio_quraan/النساء.mp3',
    'audio_quraan/المائدة.mp3',
    'audio_quraan/الأنعام.mp3',
    'audio_quraan/yasser-al-dossari-007.mp3',
    'audio_quraan/الأنفال.mp3',
    'audio_quraan/التوبة.mp3',
    'audio_quraan/يونس.mp3',
    'audio_quraan/هود.mp3',
    'audio_quraan/يوسف.mp3',
    'audio_quraan/الرعد.mp3',
    'audio_quraan/إبراهيم.mp3',
    'audio_quraan/الحجر.mp3',
    'audio_quraan/النحل.mp3',
    'audio_quraan/الإسراء.mp3',
    'audio_quraan/الكهف.mp3',
    'audio_quraan/مريم.mp3',
    'audio_quraan/طه.mp3',
    'audio_quraan/الأنبياء.mp3',
    'audio_quraan/الحج.mp3',
    'audio_quraan/المؤمنون.mp3',
    'audio_quraan/النور.mp3',
    'audio_quraan/الفرقان.mp3',
    'audio_quraan/الشعراء.mp3',
    'audio_quraan/النمل.mp3',
    'audio_quraan/القصص.mp3',
    'audio_quraan/العنكبوت.mp3',
    'audio_quraan/الروم.mp3',
    'audio_quraan/لقمان.mp3',
    'audio_quraan/السجدة.mp3',
    'audio_quraan/الأحزاب.mp3',
    'audio_quraan/سبأ.mp3',
    'audio_quraan/فاطر.mp3',
    'audio_quraan/يس.mp3',
    'audio_quraan/الصافات.mp3',
    'audio_quraan/ص.mp3',
    'audio_quraan/الزمر.mp3',
    'audio_quraan/غافر.mp3',
    'audio_quraan/فصلت.mp3',
    'audio_quraan/الشورى.mp3',
    'audio_quraan/الزخرف.mp3',
    'audio_quraan/الدخان.mp3',
    'audio_quraan/الجاثية.mp3',
    'audio_quraan/الأحقاف.mp3',
    'audio_quraan/محمد.mp3',
    'audio_quraan/الفتح.mp3',
    'audio_quraan/الحجرات.mp3',
    'audio_quraan/ق.mp3',
    'audio_quraan/الذاريات.mp3',
    'audio_quraan/الطور.mp3',
    'audio_quraan/النجم.mp3',
    'audio_quraan/القمر.mp3',
    'audio_quraan/الرحمن.mp3',
    'audio_quraan/الواقعة.mp3',
    'audio_quraan/الحديد.mp3',
    'audio_quraan/المجادلة.mp3',
    'audio_quraan/الحشر.mp3',
    'audio_quraan/الممتحنة.mp3',
    'audio_quraan/الصف.mp3',
    'audio_quraan/الجمعة.mp3',
    'audio_quraan/المنافقون.mp3',
    'audio_quraan/التغابن.mp3',
    'audio_quraan/الطلاق.mp3',
    'audio_quraan/التحريم.mp3',
    'audio_quraan/الملك.mp3',
    'audio_quraan/القلم.mp3',
    'audio_quraan/الحاقة.mp3',
    'audio_quraan/المعارج.mp3',
    'audio_quraan/نوح.mp3',
    'audio_quraan/الجن.mp3',
    'audio_quraan/المزمل.mp3',
    'audio_quraan/المدثر.mp3',
    'audio_quraan/القيامة.mp3',
    'audio_quraan/الإنسان.mp3',
    'audio_quraan/المرسلات.mp3',
    'audio_quraan/النبأ.mp3',
    'audio_quraan/النازعات.mp3',
    'audio_quraan/عبس.mp3',
    'audio_quraan/التكوير.mp3',
    'audio_quraan/الإنفطار.mp3',
    'audio_quraan/المطففين.mp3',
    'audio_quraan/الانشقاق.mp3',
    'audio_quraan/البروج.mp3',
    'audio_quraan/الطارق.mp3',
    'audio_quraan/الأعلى.mp3',
    'audio_quraan/الغاشية.mp3',
    'audio_quraan/الفجر - Copy.mp3',
    'audio_quraan/البلد - Copy.mp3',
    'audio_quraan/الشمس.mp3',
    'audio_quraan/الليل.mp3',
    'audio_quraan/الضحى.mp3',
    'audio_quraan/الشرح.mp3',
    'audio_quraan/التين.mp3',
    'audio_quraan/العلق.mp3',
    'audio_quraan/القدر.mp3',
    'audio_quraan/البينة.mp3',
    'audio_quraan/الزلزلة.mp3',
    'audio_quraan/العاديات.mp3',
    'audio_quraan/القارعة.mp3',
    'audio_quraan/التكاثر.mp3',
    'audio_quraan/العصر.mp3',
    'audio_quraan/الهمزة.mp3',
    'audio_quraan/الفيل.mp3',
    'audio_quraan/قريش.mp3',
    'audio_quraan/الماعون.mp3',
    'audio_quraan/الكوثر.mp3',
    'audio_quraan/الكافرون.mp3',
    'audio_quraan/النصر.mp3',
    'audio_quraan/المسد.mp3',
    'audio_quraan/الإخلاص.mp3',
    'audio_quraan/الفلق.mp3',
    'audio_quraan/الناس.mp3',
  ];
  static const List<String> audioAzkaar =[
    'audio_azkaar/اذكار الصباح و المساء.mp3',
    'audio_azkaar/اذكار النوم.mp3',
    'audio_azkaar/اذكار الاستيقاظ من النوم.mp3',
    'audio_azkaar/دعاء دخول الخلاء.mp3',
    'audio_azkaar/دعاء الخروج من الخلاء.mp3',
    'audio_azkaar/الذكر قبل الوضوء.mp3',
    'audio_azkaar/الذكر بعد الفراغ من الوضوء.mp3',
    'audio_azkaar/الذكر عند الخروج من المنزل.mp3',
    'audio_azkaar/الذكر عند دخول المنزل.mp3',
    'audio_azkaar/دعاء الذهاب الى المسجد.mp3',
    'audio_azkaar/دعاء دخول المسجد.mp3',
    'audio_azkaar/دعاء الخروج من المسجد.mp3',
    'audio_azkaar/اذكار الاذان.mp3',
    'audio_azkaar/دعاء الاستفتاح.mp3',
    'audio_azkaar/دعاء الركوع.mp3',
    'audio_azkaar/دعاء الرفع من الركوع.mp3',
    'audio_azkaar/دعاء السجود.mp3',
    'audio_azkaar/دعاء الجلسة بين السجدتين.mp3',
    'audio_azkaar/دعاء سجود التلاوة.mp3',
    'audio_azkaar/التشهد.mp3',
    'audio_azkaar/الصلاة على النبي بعد التشهد.mp3',
    'audio_azkaar/الدعاء بعد التشهد الاخير قبل السلام.mp3',
    'audio_azkaar/الاذكار بعد السلام من الصلاة.mp3',
    'audio_azkaar/دعاء صلاة الاستخارة.mp3',
  ]; 
}